### ============================================================================
### TEST API FOR AUTHENTICATION
### ============================================================================

### ----------------------------------------------------------------------------
### REGISTER - FIELD KOSONG SEMUA
### ----------------------------------------------------------------------------
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "",
    "email" : "",
    "password" : "",
    "re_password" : "",
    "role" : ""
}

### ----------------------------------------------------------------------------
### REGISTER - FIELD KOSONG SATU
### ----------------------------------------------------------------------------
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "user satu",
    "email" : "user1@gmail.com",
    "password" : "user1",
    "re_password" : ""
}

### ----------------------------------------------------------------------------
### REGISTER - FIELD PASSWORD SALAH
### ----------------------------------------------------------------------------
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "user satu",
    "email" : "user1@gmail.com",
    "password" : "user1",
    "re_password" : "user1a",
    "role" : "admin"
}

### ----------------------------------------------------------------------------
### REGISTER - ADMIN
### ----------------------------------------------------------------------------
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "admin satu",
    "email" : "admin1@gmail.com",
    "password" : "admin1",
    "re_password" :"admin1",
    "role" : "admin"
}

### ----------------------------------------------------------------------------
### REGISTER - USER BIASA
### ----------------------------------------------------------------------------
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "user satu",
    "email" : "user1@gmail.com",
    "password" : "user1",
    "re_password" :"user1"
}

### ----------------------------------------------------------------------------
### LOGIN - FIELD KOSONG SEMUA
### ----------------------------------------------------------------------------
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "",
    "password" : ""
}

### ----------------------------------------------------------------------------
### LOGIN - FIELD KOSONG SATU
### ----------------------------------------------------------------------------
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : ""
}

### ----------------------------------------------------------------------------
### LOGIN - FIELD PASSWORD SALAH
### ----------------------------------------------------------------------------
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "kesehatan"
}

### ----------------------------------------------------------------------------
### LOGIN - FIELD EMAIL SALAH
### ----------------------------------------------------------------------------
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "userA@gmail.com",
    "password" : "user1"
}

### ----------------------------------------------------------------------------
### LOGIN - USER BIASA
### ----------------------------------------------------------------------------
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "user1"
}

### ----------------------------------------------------------------------------
### LOGIN - ADMIN
### ----------------------------------------------------------------------------
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "admin1@gmail.com",
    "password" : "admin1"
}

### ----------------------------------------------------------------------------
### CRUD - GET ALL USER
### ----------------------------------------------------------------------------
GET http://localhost:4000/users

### ----------------------------------------------------------------------------
### CRUD - GET USERS BY ID
### ----------------------------------------------------------------------------
GET http://localhost:4000/users/1

### ----------------------------------------------------------------------------
### CRUD - GET USERS BY ROLE
### ----------------------------------------------------------------------------
GET http://localhost:4000/users/role/user

### ----------------------------------------------------------------------------
### CRUD - UPDATE USER
### ----------------------------------------------------------------------------
PATCH http://localhost:4000/users/4
Content-Type: application/json

{
    "name" : "user updated by user1",
    "email" : "user-update1@gmail.com",
    "password" : "user_update1",
    "re_password" : "user_update1"
}

### ----------------------------------------------------------------------------
### CRUD - UPDATE ROLE
### ----------------------------------------------------------------------------
PATCH http://localhost:4000/users/role/2
Content-Type: application/json

{
    "role" : "user"
}

### ----------------------------------------------------------------------------
### CRUD - DELETE USER
### ----------------------------------------------------------------------------
DELETE  http://localhost:4000/users/3