### LOGIN - KONDISI FIELD KOSONG
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "",
    "password" : ""
}

### LOGIN - KONDISI FIELD KOSONG SATU
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : ""
}

### LOGIN - KONDISI EMAIL BENAR DAN PASSWORD SALAH
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "kesehatan"
}

### LOGIN - KONDISI EMAIL SALAH DAN PASSWORD benar
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "userA@gmail.com",
    "password" : "user1"
}

### LOGIN - KONDISI EMAIL DAN PASSWORD BENAR (USER)
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "user1"
}

### LOGIN - KONDISI EMAIL DAN PASSWORD BENAR (ADMIN)
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email" : "admin1@gmail.com",
    "password" : "admin1"
}
