### REGISTER - Kosong semua
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "",
    "email" : "",
    "password" : "",
    "re_password" : "",
    "role" : ""
}

### REGISTER - Kosong satu
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "user satu",
    "email" : "user1@gmail.com",
    "password" : "user1",
    "re_password" : ""
}

### REGISTER - Password salah
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "user satu",
    "email" : "user1@gmail.com",
    "password" : "user1",
    "re_password" : "user1a",
    "role" : "admin"
}

### REGISTER - Admin
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "admin satu",
    "email" : "admin1@gmail.com",
    "password" : "admin1",
    "re_password" :"admin1",
    "role" : "admin"
}

### REGISTER - User
POST http://localhost:4000/users
Content-Type: application/json

{
    "name" : "user satu",
    "email" : "user1@gmail.com",
    "password" : "user1",
    "re_password" :"user1"
}
