openapi: 3.0.0


info:
  title: RestAPI Authentication
  version: 1.0.0
  description: |
    RestAPI Authentication with Express and Argon2
    
    - [My GitHub Repository](https://github.com/yudhaginongpratidina)


paths:
  /users:
    post:
      tags: [User]
      summary: User Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                re_password:
                  type: string
                role:
                  type: string
              required:
                - name
                - email
                - password
                - re_password
      responses:
        '201':
          description: User updated successfully
        '400':
          description: Please fill in all fields or Password did not match
        '409':
          description: Name or email already exists
        '500':
          description: Internal server error
    get:
      tags: [User]
      summary: Get all users
      responses:
        '200':
          description: Get all users
        '500':
          description: Internal server error


  /users/login:
    post:
      tags: [User]
      summary: Login User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '400':
          description: Please fill in all fields or Incorrect password
        '404' :
          description: User not found
        '200' :
          description: Login success
        '500':
          description: Internal server error

  /users/{id}:
    get:
      tags: [User]
      summary: Get User by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: User ID
      responses:
        '200':
          description: User retrieved by ID
        '404':
          description: User not found
        '500':
          description: Internal server error
    patch:
      tags: [User]
      summary: Update User
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                re_password:
                  type: string
            required:
                - name
                - email
                - password
                - re_password
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Please fill in all fields or Password did not match
        '409':
          description: Name or Email already exists
        '500':
          description: Internal server error
    delete:
      tags: [User]
      summary: Delete User
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: User ID
      responses:
        '200':
          description: User deleted successfully"
        '404':
          description: User not found
        '500':
          description: Internal server error


  /users/role/{id}:
    patch:
      tags: [User]
      summary: Update Role by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
              required:
                - role
      responses:
        '200':
          description: Role User updated successfully"
        '500':
          description: Internal server error

